---
abstract: 'CGI::Session ID driver for generating IDs based on Crypt::OpenSSL::Random'
author:
  - 'Helmut Weber <helmut.weber@bitbetrieb.de>'
build_requires:
  CGI::Session: 4
  Crypt::OpenSSL::Random: 0
  Digest::MD5: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Session-ID-crypt_openssl
provides:
  CGI::Session::ID::crypt_openssl:
    file: lib/CGI/Session/ID/crypt_openssl.pm
    version: 1.01
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
